#!/bin/bash
# Regenerate environment.yml (and requirements-cu128.txt) from uv.lock.
#
#   bash make_conda_env.sh            # default extra: cu128
#   EXTRA=cu126 bash make_conda_env.sh
#
# Run this after any change to pyproject.toml or uv.lock, so the conda file never drifts from
# what uv resolves. It does three things:
#   1. uv export  -- turns uv.lock into a pinned requirements file for one extra
#   2. sed        -- retargets spikingjelly's git URL from the openi.pcl.ac.cn mirror (which is
#                    UNREACHABLE from this cluster; pip hangs on it) to upstream GitHub. The
#                    commit hash uv pinned is kept, so the source is identical.
#   3. inline     -- writes the pins into environment.yml's pip: section. Inlined rather than
#                    `-r requirements-cu128.txt`, because pip resolves a nested -r relative to
#                    the temporary requirements file conda writes, not to this directory.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

EXTRA=${EXTRA:-cu128}
UV=${UV:-$(command -v uv || echo /home1/bkrhee/.local/bin/uv)}
REQ="requirements-${EXTRA}.txt"
OUT=${OUT:-environment.yml}
PY_VER=$(tr -d '[:space:]' < .python-version)          # 3.11 -> pinned to the venv's 3.11.9 below
PY_FULL=${PY_FULL:-3.11.9}

[ -x "$UV" ] || { echo "!! uv not found (set UV=/path/to/uv)"; exit 1; }

echo "== 1/3  uv export --extra $EXTRA"
"$UV" export --extra "$EXTRA" --no-emit-project --no-hashes --format requirements-txt -o "$REQ"

echo "== 2/3  retargeting spikingjelly to upstream GitHub"
sed -i 's|git+https://openi\.pcl\.ac\.cn/OpenI/spikingjelly\.git|git+https://github.com/fangwei123456/spikingjelly.git|' "$REQ"
grep -n "spikingjelly @" "$REQ" || echo "   (no git spikingjelly pin found -- check $REQ)"

echo "== 3/3  writing $OUT"
REQ="$REQ" OUT="$OUT" PY_FULL="$PY_FULL" EXTRA="$EXTRA" python3 - <<'PY'
import os
req, out, pyv, extra = os.environ["REQ"], os.environ["OUT"], os.environ["PY_FULL"], os.environ["EXTRA"]
pins = [l.strip() for l in open(req)
        if l.strip() and not l.strip().startswith(("#", "--"))]
idx = {"cu118": "cu118", "cu126": "cu126", "cu128": "cu128"}.get(extra)
head = f"""# Conda environment for this uv project. GENERATED by make_conda_env.sh from uv.lock --
# do not edit by hand; edit pyproject.toml and re-run the script.
#
#   conda env create -p /scratch2/$USER/envs/snn-gc -f {out}
#   conda activate /scratch2/$USER/envs/snn-gc
#
# Only Python comes from conda. Everything else is pip, because:
#   * torch is the +{extra} build from download.pytorch.org -- the conda-forge and
#     pytorch-channel builds are different binaries and would not reproduce the same kernels.
#   * spikingjelly is a git dependency, pinned to the exact commit uv.lock resolves.
name: snn-gc

channels:
  - conda-forge

dependencies:
  - python={pyv}
  - pip
  - pip:
"""
lines = [head]
if idx:
    lines.append(f"      # index first: the +{extra} versions below do not exist on PyPI\n")
    lines.append(f"      - --extra-index-url https://download.pytorch.org/whl/{idx}\n")
lines.append("      # fail fast instead of hanging if a host is unreachable\n")
lines += ["      - --timeout 60\n", "      - --retries 3\n"]
lines += [f'      - "{p}"\n' for p in pins]
open(out, "w").writelines(lines)
print(f"   {out}: {len(pins)} pinned requirements")
PY

python3 -c "
import yaml,sys; d=yaml.safe_load(open('$OUT')); p=d['dependencies'][-1]['pip']
print(f'   valid YAML: {d[\"name\"]}, python {d[\"dependencies\"][0]}, {len(p)} pip entries')" \
  || echo "   !! $OUT is not valid YAML"
